### ISSUE TITLE
Qestion about embedding

### ISSUE THREAD

**Issue by johngriffin1** [timciep/letterboxd-diary-embed#4]
I would love to add this to my neocities page but the diary never loads when I paste in the code. Am I supposed to have something else to make it work?

**Comment by timciep** [comment]
Just adding the snippet from https://letterboxd-embed.timcieplowski.com/ should do it.

If you share a link to the page you've added the snippet to, I'd be happy to take a look, and see if I can figure out what's wrong.

**Comment by johngriffin1** [comment]
[Here's](https://johngriffin.neocities.org/film) the site. Thanks!

**Comment by timciep** [comment]
It looks like this is because of Neocities' `Content-Security-Policy`.

From the console log:

```
Content-Security-Policy: The page’s settings blocked the loading of a resource (connect-src) at https://lb-embed-content.bokonon.dev/?username=johngriffin1 because it violates the following directive: “connect-src 'self' data: blob:”
```

Maybe you can configure the reconfigure policy, or get a more permissive one at different tier.  I'm not sure.  I'm not very familiar with Neocites.

Sorry, there is nothing I can do, on my side, to fix this.

**Comment by johngriffin1** [comment]
Thank you! I got it working by hosting your embed on a vercel app and then embedding that as an iframe into my site

**Comment by timciep** [comment]
Nice. That was a good idea.
